/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ScanResult = IDL.Record({
  'httpHeaders' : IDL.Text,
  'subdomains' : IDL.Vec(IDL.Text),
  'sslCertDetails' : IDL.Text,
  'dnsRecords' : IDL.Text,
  'timestamp' : Time,
  'whoisData' : IDL.Text,
  'hostingInfo' : IDL.Text,
});

export const idlService = IDL.Service({
  'getScan' : IDL.Func([IDL.Text], [ScanResult], ['query']),
  'getScanHistory' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, Time))],
      ['query'],
    ),
  'saveScan' : IDL.Func(
      [
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ScanResult = IDL.Record({
    'httpHeaders' : IDL.Text,
    'subdomains' : IDL.Vec(IDL.Text),
    'sslCertDetails' : IDL.Text,
    'dnsRecords' : IDL.Text,
    'timestamp' : Time,
    'whoisData' : IDL.Text,
    'hostingInfo' : IDL.Text,
  });
  
  return IDL.Service({
    'getScan' : IDL.Func([IDL.Text], [ScanResult], ['query']),
    'getScanHistory' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, Time))],
        ['query'],
      ),
    'saveScan' : IDL.Func(
        [
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };